### ISSUE TITLE
'No test is available' at step 4.3.2

### ISSUE THREAD

**Issue by sebrose** [tdshipley/pact-workshop-dotnet-core-v1#5]
I'm working through your workshop on OSX. All good until 4.3.2, when I get the error message:
`No test is available in /Users/seb/Projects/pact-workshop-dotnet-core-v1/YourSolution/Provider/tests/bin/Debug/netcoreapp2.0/tests.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.`

Other information
* I get the same problem when running `dotnet test` in `CompletedSolution/Provider/tests`
* I've tried giving an explicit path to XUnit using `dotnet test -a .....` but that didn't help.
* The command `dotnet test` works fine in `Consumer/tests`

This is the output from `dotnet --info` 
.NET Command Line Tools (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.13
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.0.0/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d

**Comment by sebrose** [comment]
Problem with `XUnit`.

Adding `ulimit -n 4096` to `/etc/profile` fixed the issue.

**Comment by tdshipley** [comment]
Thanks for letting me know :)
